#!/bin/sh
#
# Split lossless image into mp3 tracks for portable media.
#
# Usage:
# split-lossless [-V4] [-B160] [-b320] [in.flac [in.cue]] [out-dir]
#
set -eu

# Process options.
# lame -V4 should be close to perceptual transparency.
# lame -V6.5 (equivalent to --resample 32 -V5.2) is acceptable.
opt_V=-V4
opt_B=
opt_b=
while getopts V:B:b: opt; do
	case "$opt" in
		V) opt_V=-V${OPTARG:?} ;;
		B) opt_B=-B${OPTARG:?} ;;
		b) opt_b=-b${OPTARG:?}
		   # Adjust for maximum quality.
		   if [ "$opt_b" = '-b320' ]; then
			   opt_V='-h'
		   fi ;;
	esac
done
shift "$(($OPTIND-1))"

# Process args.
in=
cue=
outdir=.
if [ -n "${1-}" ] && [ -z "${1##*.flac}" -o -z "${1##*.ape}" ]; then
	in=$1
	shift
	if [ -n "${1-}" ] && [ -z "${1##*.cue}" ]; then
		cue=$1
		shift
	fi
fi
if [ -n "${1-}" ]; then
	outdir=$1
	shift
fi
if [ $# -gt 0 ]; then
	echo >&2 "${0##*/}: too many arguments"
	exit 1
fi

# Autodetect input.
if [ -z "$in" ]; then
	if set *.flac && [ $# = 1 ] && [ -f "$1" ]; then
		in=$1
	elif set *.ape && [ $# = 1 ] && [ -f "$1" ]; then
		in=$1
	else
		echo >&2 "${0##*/}: input not recognized"
		exit 1
	fi
fi
if [ -z "$cue" ]; then
	cue=${in%.*}.cue
	if [ -f "$cue" ]; then
		: good
	elif set *.cue && [ $# = 1 ] && [ -f "$1" ]; then
		cue=$1
	else
		echo >&2 "${0##*/}: cue sheet not found"
		exit 1
	fi
fi

# Setup output directory.
mkdir -p "$outdir"
if set "$outdir"/*.mp3 && [ $# -gt 1 -o -e "$1" -o -L "$1" ]; then
	echo >&2 "${0##*/}: directory $outdir already has mp3 files"
	exit 1
fi

# Decode and compress.
set -o pipefail
if [ -z "${in##*.flac}" ]; then
	if [ -e /dev/stdin ]; then
		# lame will show the progress and histogram.
		flac -dc -s "$in" |
		lame $opt_V $opt_B $opt_b /dev/stdin "$outdir"/.out.mp3
	else
		# flac will show the progress.
		flac -dc "$in" |
		lame $opt_V $opt_B $opt_b - "$outdir"/.out.mp3
	fi
else
	# mac will show the progress.
	mac "$in" - -d |
	lame $opt_V $opt_B $opt_b - "$outdir"/.out.mp3
fi
set +o pipefail

# Propagate year and genre.
if grep -qs '^REM DATE \|^REM GENRE ' "$cue" &&
 ! grep -qs ' REM DATE \| REM GENRE ' "$cue"; then
	perl -pe <"$cue" >"$outdir"/.out.cue '
		if (/^REM DATE |^REM GENRE /) {
			$tags .= $_;
		}
		if (/^(\s+)TITLE/) {
			$space = $1;
			$tags =~ s/^\s*/$space/gm;
			print $tags;
		}'
else
	cat <"$cue" >"$outdir"/.out.cue
fi

# Split into tracks.
mp3splt -c "$outdir"/.out.cue -d "$outdir" -o '@n @t' "$outdir"/.out.mp3
rm "$outdir"/.out.mp3 "$outdir"/.out.cue
