#!/bin/sh
set -eu

if set *.cue && [ $# = 1 ] && [ -f "$1" ]; then
	cue=$1
else
	echo >& "cue sheet not found"
fi

if set *.flac && [ $# = 1 ] && [ -f "$1" ]; then
	mkdir -p tmp
	flac -dc "$1" >tmp/out.wav
elif set *.ape && [ $# = 1 ] && [ -f "$1" ]; then
	mkdir -p tmp
	mac "$1" tmp/out.wav -d
else
	echo >& "lossless format not recognized"
	exit 1
fi

lame -V6.5 tmp/out.wav tmp/out.mp3
rm -rf split
mkdir split
mp3splt -c "$cue" -d split -o '@n @t' tmp/out.mp3
rm -rf tmp

tag_mp3()
{
	local no="$1" mp3="$2" tag
	for tag in 'title %t -t' 'album %T -l' 'artist %p -a' 'comment %c -c' 'trackno %n -n'; do
		set -- $tag
		local name="$1" fmt="$2" opt="$3" val
		val=$(cueprint -n "$no" -t "$fmt" "$cue")
		[ -n "$val" ] || continue
		mp3info $opt "$val" "$mp3"
	done
	local year genre
	year=$(sed -n '/^REM DATE \(19[0-9][0-9]\|20[0-9][0-9]\).*/{s//\1/;p;q}' "$cue")
	if [ -n "$year" ]; then
		mp3info -y "$year" "$mp3"
	fi
	genre=$(cueprint -n "$no" -t "%g" "$cue")
	[ -n "$genre" ] ||
	genre=$(sed -n '/^REM GENRE \([A-Z][a-z]*\).*/{s//\1/;p;q}' "$cue")
	if [ -n "$genre" ]; then
		mp3info -g "$genre" "$mp3"
	fi

}

no=1
for mp3 in split/*.mp3; do
	tag_mp3 "$no" "$mp3"
	no=$(($no+1))
done
